#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# ///

import json
import sys
import re
import subprocess


def create_timeout_error_message(command_type, wanted_timeout, current_timeout):
    minutes = int(wanted_timeout / 60 / 1000)
    return f"You must set a timeout of {wanted_timeout}ms ({minutes} minutes) for {command_type} commands. This is not a test timeout error. Please retry the command with 'timeout': {wanted_timeout} in the tool parameters."


def check_git_branch_creation(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        if re.search(r'\bgit\s+checkout\s+-b\b', command):
            try:
                result = subprocess.run(['git', 'branch', '--show-current'],
                                        capture_output=True, text=True, timeout=5)
                if result.returncode == 0:
                    current_branch = result.stdout.strip()
                    if current_branch != 'main':
                        decision = {
                            "decision": "block",
                            "reason": f"New branches should only be created from 'main', but you're currently on '{current_branch}'. You're already on the correct branch for your work, so no need to create a new one."
                        }
                        print(json.dumps(decision))
                        sys.exit(1)
            except (subprocess.TimeoutExpired, subprocess.SubprocessError, FileNotFoundError):
                pass


def check_git_commit_branch(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        if re.search(r'\bgit\s+commit\b', command):
            try:
                result = subprocess.run(['git', 'branch', '--show-current'],
                                        capture_output=True, text=True, timeout=5)
                if result.returncode == 0:
                    current_branch = result.stdout.strip()
                    if current_branch == 'main':
                        decision = {
                            "decision": "block",
                            "reason": "Direct commits to the 'main' branch are not allowed. Please create a feature branch first (e.g., 'git checkout -b feature/your-feature-name') and commit your changes there, then create a pull request."
                        }
                        print(json.dumps(decision))
                        sys.exit(1)
            except (subprocess.TimeoutExpired, subprocess.SubprocessError, FileNotFoundError):
                pass


def check_git_no_verify(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        if re.search(r'\bgit\s+(?:(?!-m|<<)[^;|&\n])*--no-verify\b', command):
            decision = {
                "decision": "block",
                "reason": "The '--no-verify' flag is not allowed in git commands. You are never allowed to skip hooks"
            }
            print(json.dumps(decision))
            sys.exit(1)


def check_git_commit_boilerplate(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        if re.search(r'\bgit\s+commit\b', command):
            boilerplate_patterns = [
                r'Generated with Claude Code',
                r'Co-Authored by Claude',
                r'Generated with \[Claude Code\]',
                r'Co-Authored-By:\s*Claude',
                r'<noreply@anthropic\.com>',
                r'claude\.ai/code',
                r'Generated by Claude',
                r'Created with Claude Code',
                r'Assisted by Claude',
                r'With help from Claude',
                r'@anthropic\.com',
            ]
            for pattern in boilerplate_patterns:
                if re.search(pattern, command, re.IGNORECASE):
                    decision = {
                        "decision": "block",
                        "reason": "Boilerplate code patterns are not allowed in git commit messages. Please remove references to Claude Code, co-authorship with Claude, or Anthropic email addresses from your commit message and try again."
                    }
                    print(json.dumps(decision))
                    sys.exit(1)


def check_pr_create_boilerplate(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        if re.search(r'\bgh\s+pr\s+create\b', command):
            boilerplate_patterns = [
                r'Generated with Claude Code',
                r'Co-Authored by Claude',
                r'Generated with \[Claude Code\]',
                r'Co-Authored-By:\s*Claude',
                r'<noreply@anthropic\.com>',
                r'claude\.ai/code',
                r'Generated by Claude',
                r'Created with Claude Code',
                r'Assisted by Claude',
                r'With help from Claude',
                r'@anthropic\.com',
                r'AI-generated',
                r'AI generated',
                r'Generated by AI',
                r'Created by AI',
                r'Built with AI',
            ]
            for pattern in boilerplate_patterns:
                if re.search(pattern, command, re.IGNORECASE):
                    decision = {
                        "decision": "block",
                        "reason": "Boilerplate patterns are not allowed in PR titles or descriptions. Please remove references to Claude Code, AI generation, co-authorship with Claude, or Anthropic email addresses from your PR content and try again."
                    }
                    print(json.dumps(decision))
                    sys.exit(1)


def check_pr_comment_boilerplate(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        if re.search(r'\bgh\s+api\s+repos/.+/issues/\d+/comments\b', command):
            boilerplate_patterns = [
                r'Generated with Claude Code',
                r'Co-Authored by Claude',
                r'Generated with \[Claude Code\]',
                r'Co-Authored-By:\s*Claude',
                r'<noreply@anthropic\.com>',
                r'claude\.ai/code',
                r'Generated by Claude',
                r'Created with Claude Code',
                r'Assisted by Claude',
                r'With help from Claude',
                r'@anthropic\.com',
                r'AI-generated',
                r'AI generated',
                r'Generated by AI',
                r'Created by AI',
                r'Built with AI',
            ]
            for pattern in boilerplate_patterns:
                if re.search(pattern, command, re.IGNORECASE):
                    decision = {
                        "decision": "block",
                        "reason": "Boilerplate patterns are not allowed in PR comments. Please remove references to Claude Code, AI generation, co-authorship with Claude, or Anthropic email addresses from your comment and try again."
                    }
                    print(json.dumps(decision))
                    sys.exit(1)


def check_git_checkout_main(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        if re.search(r'\bgit\s+checkout\s+main\b', command):
            decision = {
                "decision": "block",
                "reason": "Claude isn't allowed to checkout the main branch. Please ask the user what to do instead."
            }
            print(json.dumps(decision))
            sys.exit(1)


def add_timeout_to_git_commit(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        timeout = tool_input.get('timeout')
        if re.search(r'\bgit\s+commit\b', command):
            wanted_timeout = 900000
            if timeout != wanted_timeout:
                decision = {
                    "decision": "block",
                    "reason": create_timeout_error_message("Git commit", wanted_timeout, timeout)
                }
                print(json.dumps(decision))
                sys.exit(1)


def add_timeout_to_git_push(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        timeout = tool_input.get('timeout')
        if re.search(r'\bgit\s+push\b', command):
            wanted_timeout = 900000
            if timeout != wanted_timeout:
                decision = {
                    "decision": "block",
                    "reason": create_timeout_error_message("Git push", wanted_timeout, timeout)
                }
                print(json.dumps(decision))
                sys.exit(1)


def add_timeout_to_gh_run_watch(tool_name, tool_input):
    if tool_name == 'Bash':
        command = tool_input.get('command', '')
        timeout = tool_input.get('timeout')
        if re.search(r'\bgh\s+run\s+watch\b', command):
            wanted_timeout = 1800000
            if timeout != wanted_timeout:
                decision = {
                    "decision": "block",
                    "reason": create_timeout_error_message("gh run watch", wanted_timeout, timeout)
                }
                print(json.dumps(decision))
                sys.exit(1)


def main():
    try:
        input_data = json.load(sys.stdin)
        tool_name = input_data.get('tool_name', '')
        tool_input = input_data.get('tool_input', {})

        add_timeout_to_git_commit(tool_name, tool_input)
        add_timeout_to_git_push(tool_name, tool_input)
        add_timeout_to_gh_run_watch(tool_name, tool_input)
        check_git_commit_branch(tool_name, tool_input)
        check_git_branch_creation(tool_name, tool_input)
        check_git_no_verify(tool_name, tool_input)
        check_git_commit_boilerplate(tool_name, tool_input)
        check_pr_create_boilerplate(tool_name, tool_input)
        check_pr_comment_boilerplate(tool_name, tool_input)
        check_git_checkout_main(tool_name, tool_input)

        sys.exit(0)
    except json.JSONDecodeError:
        sys.exit(0)
    except Exception:
        sys.exit(0)


if __name__ == '__main__':
    main()
